mozilla/node-fx-runner

bin/fx-runner, lib/run.js
@jsantell for Fx Hello I'd like to run Firefox with '-CreateProfile loop-dev', but with the current implementation that isn't possible.
Loop PR: mozilla/loop#59
I updated the source and tests a bit to accommodate for this and also support passing multiple additional arguments to the binary.
=> Add support for multiple and compound binary arguments

.travis.yml
Run tests on travis on the same platforms as jpm. Most notably instead of io.js run them on node.js version 4 and 5.
=> Add node 4 and 5 instead of iojs to travis

lib/utils.js, package.json, test/run/test.utils.js
(I keep my Firefoxen in `/Applications/Local` because I hate myself apparently.  This patch lets me run firefox without specifying the full path all over the place.  Oh, and it adds `firefoxdeveloperedition` as a target, cause everyone loves the Developer Edition!  😃)
=> Use mdfind to find the locations of the apps on OS X.

lib/utils.js, package.json, test/run/test.utils.js
This should behave the same as it already does, just even better on linux. Instead of fixed path mappings it just uses binary name mappings. If a platform uses a different name, like Ubuntu uses `firefox-trunk` for Nightly that will still work, since which is invoked if the binaryPath does not contain a directory separator. I've also regrouped some of the logic to only affect the necessary code paths.
This should fix #2
=> Use which to detect binary location on linux

lib/utils.js, test/run/test.utils.js
Since I have a custom build of Firefox, mdfind returns this:
````
$ mdfind "kMDItemCFBundleIdentifier == 'org.mozilla.nightly'"
/Users/kumar/src/fx-team/objdir-frontend/dist/Nightly.app
/Applications/FirefoxNightly.app
````
It should only find the official nightly app
=> Prefer the official app per channel on OS X

lib/run.js, test/run/test.run.js
This PR remove a dash from the `start-debugger-server` command line flag, because `--start-debugger-server` is not recognized by the Firefox executable on Windows systems, and on the contrary `-start-debugger-server` works as expected on all the supported platforms.
The above is the reason of mozilla/web-ext#317 on windows, which is not a Firewall issue and it will be fixed once we release an updated fx-runner npm package and update the dependency in webe-ext accordingly.
=> Fix unrecognized command line flag --start-debugger-server on Windows

bin/fx-runner, lib/run.js, package.json, test/run/test.run.js
Fix [Several arguments in --binary-args doesn't work when used in jpm run command. · Issue #10](https://github.com/mozilla-jetpack/node-fx-runner/issues/10)
Split `binary-args` string into an array and concats to the `args` array.
Spaces are left as they are if the argument is quoted.
e.g. `"-a b -c \"d e\""` will concat `["-a", "b", "-c", "\"d e\""]`
=> Split binary-args in lib/run.js

lib/utils.js
Might fix https://github.com/mozilla-jetpack/node-fx-runner/issues/26
=> Handle case where key is null on Win32

package.json, test/run/test.run.js
It's deprecated, but not actually used anywhere, so now dependents won't see
warnings like (upon `npm install`):
npm WARN deprecated fs-promise@0.3.1: Use mz or fs-extra^3.0 with Promise Support
or (upon `yarn install`):
warning web-ext > fx-runner > fs-promise@0.3.1: Use mz or fs-extra^3.0 with Promise Support
=> Remove unused `fs-promise` dependency

lib/utils.js
Support Firefox 64-bit on Windows 64-bit as default and fallback to Firefox 32-bit.
See https://github.com/mozilla/web-ext/issues/213
=> Support Firefox 64-bit on Windows 64-bit as default

lib/utils.js
=> Implement the firefoxdeveloperedition alias for Windows.  Fixes #28

lib/utils.js, test/run/test.utils.js
There is at least one distribution, Arch Linux, which is using `firefox-developer-edition` as an executable name, and this is coherent with the other aliases:
https://github.com/mozilla-jetpack/node-fx-runner/blob/e72b066326e1abd0cd1a4a0d556daf1e6bcc2370/lib/utils.js#L121-L123
=> Add firefoxdeveloperedition alias on Linux

.travis.yml, README.md, package-lock.json, package.json, test/run/test.utils.js
I did some chores and bumped the version to 1.0.12. Please rebase or merge instead of squashing all commits to keep the history readable.
The main driver for this version bump is #43 and https://github.com/mozilla/web-ext/issues/1906 , but since I was at it, I also bumped mocha to quelch npm audit warnings, and fixed an issue that caused a test failure in Node 12.
=> Chores and version bump to 1.0.12

lib/utils.js, test/run/test.utils.js
This change resolves the issue described in issue #47.
Recent versions of Firefox Developer Edition and Firefox Nightly use spaces in their app names—`Firefox Developer Edition.app` and `Firefox Nightly.app` respectively.
I tried to be sensitive to preserving some backwards compatibility with older names, in case folks are still using them. My local testing (which I acknowledge may miss a historical case I'm not aware of) succeeded in launching the correct version of Firefox when I renamed `/Applications/Firefox Nightly.app` -> `/Applications/FirefoxNightly.app` and `Firefox Developer Edition.app` -> `FirefoxDeveloperEdition.app`.
All of the tests supplied pass for me.
My manual testing included successfully running the following commands with the expected results:
```
./bin/fx-runner -b …
```
=> accurately resolve aliases on macOS

lib/utils.js, test/run/test.utils.js
Fix for #73. After revising my approach I'm fairly certain it works correctly. I extracted a couple of functions from `normalizeBinary` for getting the relevant registry values as promises and test in turn both registry hives before falling back on the standard program files path as before.
Tested by editing the registry to the following circumstances:
- Both keys in place, opens Firefox correctly
- Only HKLM key in place, old path found as before
- Both keys missing, falls back on program files as before
=> Look for Firefox in HKCU as well as HKLM (fix #73)

.circleci/config.yml
Fixes release_tag job failure (e.g. see [this failed job](https://app.circleci.com/pipelines/github/mozilla/node-fx-runner/57/workflows/d3ad92f3-955d-4893-a97c-654e2ffcf2b4/jobs/192/parallel-runs/0/steps/0-104)), due to missing a project checkout to publish on npm.
The underlying issue is that we are not persisting the project repo in the build steps, which are the ones that are actively checking out the project sources, as an example as we do in the [webextension-polyfill circleci config here](https://github.com/mozilla/webextension-polyfill/blob/e48cc39170f558e708f7309a30cfee9ea7138be5/.circleci/config.yml#L138).
=> chore(circleci): Added missing persist_project_repo step in build jobs

.circleci/config.yml
Should fix failure triggered in the last run for the release_tag job (see [failure log here](https://app.circleci.com/pipelines/github/mozilla/node-fx-runner/60/workflows/61cd65a2-b787-4ba1-ac37-3b09446e177a/jobs/202/parallel-runs/0/steps/0-101)).
We do the [same for web-ext](https://github.com/mozilla/web-ext/blob/d07b9238ed91c9bc8f475d9890b0509e12fe4350/.circleci/config.yml#L213), because unlike webextension-polyfill both node-fx-runner and web-ext circle-ci jobs runs on more than one nodejs version as in this case.
=> chore(circleci): persist_project_repo step should run on the build running on nodejs_current

package.json
While I was releasing v1.1.0 yesterday I did notice that the package metadata could use an update.
In this PR:
- updated the repo url to remove link to the obsolete mozilla-jetpack organization (the url was redirected to the new one, but it does still make sense to update it to point directly to the repo in the mozilla organization)
- set the author field to `"Mozilla Add-ons Team"` (like in the addons-linter package.json file)
- I removed the maintainers field (npm should be automatically setting it to the npm login that publish the releases)
I was tempted to move the previous list of mantainers into the contributors field, but honestly the contributors list from the github repo (or computed from the git commits authors) is a better way to get to an updated list of contributors (and the …
=> chore: Updated package.json metadata

lib/run.js, test/run/test.run.js
I decided to add a new parameter to be backward compatible just in case.. I don't think it matters much but also I don't know the history of the project and it feels weird to add parameters at the beginning of the list (with `unshift()`). There might be a reason..
=> feat: add an option to change the final order of the command arguments

lib/utils.js, package-lock.json, package.json, test/run/test.run.js, test/run/test.utils.js
- Part of https://github.com/mozilla/node-fx-runner/issues/89
I'll work on each of these dependencies separately, altering as little as possible. The codebase is ancient and I don't want to rock the boat without a linter.
CI points to Node 18+ compatibility. `global.Promise` has been in Node since v0.12.0 so we're well covered.
=> Drop `when` dependency

bin/fx-runner, package-lock.json, package.json, test/run/test.run.js
- closes https://github.com/mozilla/node-fx-runner/issues/89
=> Bump commander from v2 to v12

lib/utils.js, package-lock.json, package.json, test/run/test.utils.js
In retrospect, I should have updated `which` before or together with [dropping `when`](https://github.com/mozilla/node-fx-runner/pull/136) 😅 but hindsight is 20/20
=> Bump `which` to v4
